### ISSUE TITLE
Cronograma | Embarcados

### ISSUE THREAD

**Issue by izabellaalves** [izabellaalves/pi1-juliana-grupo2#7]

**Comment by MatsFidelis** [comment]
@raqueleucaria -> Nosso cronograma se encontra no seguinte Link:

https://docs.google.com/spreadsheets/d/1aKLt7fKGSdI-hYIbCueMNfdUsx1YjOywmxIJQmBudMQ/edit#gid=0

Fizemos uma divisão em 4 cores apenas para diferencias atividades que estariam sendo executadas simultaneamente.
