### ISSUE TITLE
Cronograma | Dados

### ISSUE THREAD

**Issue by izabellaalves** [izabellaalves/pi1-juliana-grupo2#8]

**Comment by esmsena** [comment]
## Conclusão

Agradeço a colaboração de todos neste processo de elaboração do cronograma. Com base nas discussões e revisões realizadas, concluímos o cronograma final que reflete as etapas e prazos necessários para a parte de dados. Deixarei o link do cronograma na planilha a seguir, e também o upload do conograma atualizado está no repositório para referência futura. 

## Link da planilha 

https://docs.google.com/spreadsheets/d/1DJepIfusDkRxKGqHgvKUXuDxTRfU1aYMBAsmRoOhpVA/edit?usp=sharing

## Agradecimento 

Se houver alguma dúvida ou sugestão adicional, por favor, fiquem à vontade para comentar. Obrigado novamente pelo empenho de todos!
