### ISSUE TITLE
Cronograma | Estruturas/Energia

### ISSUE THREAD

**Issue by izabellaalves** [izabellaalves/pi1-juliana-grupo2#9]

**Comment by itsmewall** [comment]
@raqueleucaria,

nosso cronograma se encontra [aqui](https://docs.google.com/spreadsheets/d/1eG_hJav7v9xkmOleL8CWwzPHaN0bN51XLKWfe0LJlT0/edit?usp=sharing).

Apenas para constar, os itens em **negrito** são os que importam para o relatório final.
